# Generated by Django 6.0.4 on 2026-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Task's name")),
                ('done', models.BooleanField(default=False)),
                ('date', models.DateTimeField(verbose_name="Task's date")),
                ('color', models.CharField(default='blue', verbose_name='Pick category')),
                ('star_task', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
